---
- name: Backup original SSH config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    remote_src: yes
    force: no

- name: Configure SSH hardening
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin ', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication ', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication ', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?AuthorizedKeysFile ', line: 'AuthorizedKeysFile .ssh/authorized_keys' }
    - { regexp: '^#?PermitEmptyPasswords ', line: 'PermitEmptyPasswords no' }
    - { regexp: '^#?ChallengeResponseAuthentication ', line: 'ChallengeResponseAuthentication no' }
    - { regexp: '^#?UsePAM ', line: 'UsePAM yes' }
    - { regexp: '^#?X11Forwarding ', line: 'X11Forwarding no' }
    - { regexp: '^#?PrintMotd ', line: 'PrintMotd no' }
    - { regexp: '^#?TCPKeepAlive ', line: 'TCPKeepAlive yes' }
    - { regexp: '^#?ClientAliveInterval ', line: 'ClientAliveInterval 300' }
    - { regexp: '^#?ClientAliveCountMax ', line: 'ClientAliveCountMax 2' }
    - { regexp: '^#?MaxAuthTries ', line: 'MaxAuthTries 3' }
    - { regexp: '^#?MaxSessions ', line: 'MaxSessions 2' }
    - { regexp: '^#?Protocol ', line: 'Protocol 2' }
    - { regexp: '^#?LogLevel ', line: 'LogLevel VERBOSE' }
  notify: restart ssh

- name: Configure allowed users
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowUsers '
    line: 'AllowUsers {{ ssh_allowed_users | join(" ") }}'
    backup: yes
  when: ssh_allowed_users is defined
  notify: restart ssh

- name: Configure strong ciphers and MACs
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      # Strong Ciphers and MACs
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SSH CRYPTO"
    backup: yes
  notify: restart ssh

- name: Validate SSH configuration
  command: sshd -t
  changed_when: false

- name: Ensure SSH service is enabled
  systemd:
    name: ssh
    enabled: yes
