---
- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  register: update_result
  retries: 3
  delay: 10

- name: Install essential security packages
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
      - update-notifier-common
      - curl
      - wget
      - vim
      - htop
      - ufw
      - rsyslog
      - logrotate
    state: present

- name: Configure automatic security updates
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    mode: '0644'
    backup: yes

- name: Configure unattended upgrades
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}";
          "${distro_id}:${distro_codename}-security";
          "${distro_id}:${distro_codename}-updates";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "false";
    mode: '0644'
    backup: yes

- name: Set kernel parameters for security
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  loop: "{{ kernel_parameters }}"
  when: kernel_parameters is defined

- name: Disable IPv6 if configured
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: disable_ipv6 | default(false)

- name: Remove unnecessary packages
  apt:
    name:
      - telnet
      - rsh-client
      - rsh-redone-client
    state: absent
    autoremove: yes

- name: Ensure rsyslog is running
  systemd:
    name: rsyslog
    state: started
    enabled: yes

- name: Configure log rotation
  copy:
    dest: /etc/logrotate.d/custom
    content: |
      /var/log/*.log {
          daily
          missingok
          rotate 52
          compress
          delaycompress
          notifempty
          create 0644 root root
      }
    mode: '0644'
