all:
  children:
    azure_vms:
      hosts:
        demo-vm:
          ansible_host: 172.191.96.102
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        environment_name: "{{ env | default('dev') }}"
        vm_size: Standard_B1s
        location: eastus
